### PR TITLE
IFI-276 Don't ignore --config when .generator-liferay-bundle.json does not exist

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by john-co** [comment]
@izaera On Windows, it looks like it fixed a part of the original issue however, something else is not working. I get this error when script gets to `generate-samples.js`
https://gist.github.com/john-co/4476549c9a67719a8a2945d0e38a4c9c

**Comment by john-co** [comment]
@izaera same for MacOS https://gist.github.com/john-co/2d829c5f00565f3e8421ec60f71d1a90

**Comment by john-co** [comment]
After rebuilding npm, the script works fine. I think this would be good to push in as is and continue testing on vpn servers.

**Comment by izaera** [comment]
I'll merge this into `develop` branch of the upstream repo 👍

**Pull request closed without merging**
